server:
  port: 8090

spring:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pgadmin
    username: postgres
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.spring.hero.pojo
#  mapper-locations: classpath*:com/spring/hero/mapper/*.xml
  mapper-locations: classpath:mybatis/*.xml